package:
  name: metalncrna
  version: "1.1.4"

source:
  path: ..

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - metalncrna = metalncrna.cli:main

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools >=61.0
  run:
    - python >=3.8
    - mamba
    - pandas
    - biopython
    - plotly
    - pyyaml
    - rich
    - matplotlib-base
    - matplotlib-venn

test:
  commands:
    - metalncrna --help

about:
  home: https://github.com/LaBiOmicS/metaLncRNA
  license: MIT
  license_file: LICENSE
  summary: 'A portable and modular meta-predictor for identifying Long Non-coding RNAs (lncRNAs).'
  dev_url: https://github.com/LaBiOmicS/metaLncRNA
  doc_url: https://github.com/LaBiOmicS/metaLncRNA/blob/main/README.md

extra:
  recipe-maintainers:
    - FabianoMenegidio
